### ISSUE TITLE
mockIndexedDBOpenDBRequest fails in IE

### ISSUE THREAD

**Issue by nevinsjr** [szimmers/mock-indexeddb#1]
First of all, this project is GREAT!  Saving me tons of time in my unit tests on a new development project.  I haven't had a chance to fork it in order to contribute, so I thought I would log this finding as an issue.  The issue is at line 417, in new CustomEvent, which fails in IE 11(in my case).  I am running my unit tests in Chrome, Firefox and IE.  I fixed by replacing

var event = new CustomEvent("success", { bubbles: false, cancelable: true });

with 

var event = document.createEvent("CustomEvent");
event.initCustomEvent("success", false, false, { bubbles: false, cancelable: true });

**Comment by davidpricedev** [comment]
Thanks for the fix, I ran into that issue with phantomjs too.

**Comment by szimmers** [comment]
a rather belated thank you for the fix; it's finally integrated!
